spring.application.name=MediaMS
server.port = 8084
spring.datasource.url = jdbc:mysql://localhost:3306/mediadb
spring.datasource.username = root
spring.datasource.password = Dh@131204

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
